### PR TITLE
Removed unused docs/README.md

### PR DESCRIPTION
**Pull request by julienanquetil**
Fix Path to image

### CODE REVIEW

**Review by avstudnitz — DISMISSED** [review]

**Comment by gowrizrh** [comment]
this file is leftover from a legacy migration and should be considered to be removed instead. this isn't the main `README`

**Comment by fballiano** [comment]
@gowrizrh should we remove the whole `/docs` or just `docs/README.md`?

**Comment by gowrizrh** [comment]
just `docs/README.md`

**Comment by fballiano** [comment]
@julienanquetil would you remove the docs/readme completely instead?

**Comment by julienanquetil** [comment]
@fballiano PR updated :) thanks

**Review by gowrizrh — APPROVED** [review]

**Pull request merged**
